name: Saving blobs
 
on:
    push:
        branches: [ main ]
 
    schedule:
        - cron: '0 0,12 * * *'

env:
    TZ: UTC

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - 
                uses: actions/checkout@v2
            - 
                name: Saving shsh
                run: |
                    wget ${{ secrets.jsonURL }} -O data.json
                    python3 main.py
